---
title: "Exercice1"
output: github_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
```


# Reading the File

```{r  message=FALSE}
library(readr)
Connections <- read_csv("C:/Users/Mehdi/Desktop/2022-ona-assignements/orgb_exercie1/Connections.csv")
#View(Connections)

head(Connections)

df = Connections

```

# Count of values

```{r  message=FALSE}
library(dplyr)
library("tidyverse")
library("igraph")

df = df %>% drop_na(Company)

my_count <- df %>%
  group_by(Company) %>%
  count(Company, sort=TRUE) 

my_count
```
# Create Nodes and Edges
```{r  message=FALSE}

df = df %>%  unite(name, c("First Name", "Last Name"))

nodes = df %>% select(c("name", "Company"))
nodes = nodes %>% rowid_to_column("id")

nodes %>% head(5)


edges = df %>% select(c(name, Company)) %>% left_join(nodes %>% select(c(id,name)), by = c("name"="name"))
edges = edges %>% left_join(edges, by = "Company", keep=FALSE) %>% select(c("id.x", "id.y", "Company")) %>% filter(id.x!=id.y)

colnames(edges) = c("x", "y", "Company")
edges %>% head(5)

```
# Plotting the network graph
``` {r message=FALSE}

#install.packages('tidygraph')
#install.packages('ggraph')
library(tidygraph)
library(ggraph)

my_graph = tbl_graph(edges = edges, nodes = nodes, directed = FALSE)

ggraph(my_graph) + 
  geom_edge_link(aes(color = Company), show.legend = FALSE) + 
  geom_node_point()+
  theme_graph()


```
