---
title: "Ex5"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# What is complex contagion and how it’s different from simple contagion

In the simple contagion model: you only need one person connected to you to be infected by the “virus”. You still need to be exposed to the “virus” to be infected.

In the complex contagion model, the “infection” depends on the number of people infected in your network (people you’re connected to). There is a certain threshold that needs to be reached to be infected by the “virus”. This threshold corresponds to the ratio of infected connections on the total number of connections.

The way the virus can spread in these two types of models is different. Indeed, in a simple contagion model, a high number of connections leads to high virus spread within the network. In the opposite, the higher is the number of connections, the lower is the virus spreading in the network. This difference is explained by the fact that a single person can more easily “infect” a single person than a whole group at once. For example, a person can more easily convince a connection of a fake news rather than a whole group at once. Indeed, the threshold in the complex contagion model is more difficult to reach as there will always be skeptical people.

# What does complex contagion mean for diffusion of behaviors in organization?

The complex contagion for the diffusion of behaviors in an organization means that within a divided network with many disconnections, or within a very dense but well-connected network, the diffusion of behaviors will be very weak. Indeed, in this type of structure, a person is less likely to be infected because of the relatively high number of connections that are not. As long as the threshold is not reached, the person will not adopt the new behavior. Thus, in order to adopt new behaviors in an organization, the right amount of people with that behavior needs to be connected to the ones we want to infect. This can be seen as an optimization problem in which we want to maximize the number of people to infect (meaning a number of connections at least equal to the threshold) subject to peoples’ constraints. We can also minimize this number for the bad behaviors.

# How to use the threshold model to better manage

As explained before, a certain threshold in the connections needs to be reached in order to have a person adopting the behavior. The first step should then be to determine these thresholds for each type of behaviors (good or bad). This can be made by analyzing historical behaviors adoption within the organization. Once these thresholds are quantified, we can manage to act on the connections to promote or stop a type of behavior within the network and the organization. 

For example, during the pandemic, the experts started by determining how many people an infected person can infect. Once this threshold was identified, the governments limited the number of people we can meet with in our personal network. Depending on the threshold, we were able to meet by 3, 5 or 10 people in a house.

Thus, to spread a good behavior such as knowledge transfer and learning within the organization, we need to reach the threshold of connections on people that we want to be “infected” by this behavior. The goal is then to connect these people with enough people with that behavior (according to the threshold) in order to have them adopting that behavior. 

Regarding bad behaviors such as toxic or unproductive behaviors, the goal is to avoid reaching the threshold to save other people from being infected. Connections between these people and the one that are not infected needs to be limited. However, we can try to fix their behavior by connecting them with enough people with an opposed behavior and those with a prosocial behavior.
In both cases, the goal is to manage the connections within the network to decide to spread or not a type of behavior by connecting the right amount of people to the right people.

